# Generated by Django 5.2.17 on 2026-08-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('joint', 'Joint'), ('separate', 'Separate')], max_length=24, unique=True)),
                ('version', models.CharField(max_length=120)),
                ('artifact_directory', models.CharField(max_length=500)),
                ('queue_macro_f1', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('priority_accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fixed', models.BooleanField(default=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('family',),
            },
        ),
    ]
