# Generated by Django 5.2.17 on 2026-08-21 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('issue_type', models.CharField(blank=True, choices=[('Incident', 'Incident'), ('Request', 'Request'), ('Problem', 'Problem'), ('Change', 'Change')], max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('WAITING_FOR_SUPPORT', 'Waiting for Support'), ('WAITING_FOR_CUSTOMER', 'Waiting for Customer'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed')], default='DRAFT', max_length=32)),
                ('priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16)),
                ('routing_failed', models.BooleanField(default=False)),
                ('routing_failure_reason', models.TextField(blank=True)),
                ('model_family', models.CharField(blank=True, max_length=24)),
                ('model_version', models.CharField(blank=True, max_length=120)),
                ('predicted_queue', models.CharField(blank=True, max_length=120)),
                ('predicted_priority', models.CharField(blank=True, max_length=16)),
                ('queue_confidence_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priority_confidence_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_method', models.CharField(blank=True, max_length=80)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('first_staff_reply_at', models.DateTimeField(blank=True, null=True)),
                ('last_customer_reply_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_for_customer_since', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer_review_until', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_source', models.CharField(blank=True, choices=[('CUSTOMER', 'Customer marked resolved'), ('AUTOMATIC_NO_CUSTOMER_REPLY', 'Automatic no-reply resolution'), ('ADMIN_FORCE_CLOSE', 'Administrator force close'), ('SYSTEM', 'System closure')], max_length=40)),
                ('force_close_reason', models.TextField(blank=True)),
                ('first_reply_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_clock_started_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_elapsed_seconds', models.PositiveBigIntegerField(default=0)),
                ('first_reply_sla_met', models.BooleanField(blank=True, null=True)),
                ('resolution_sla_met', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='force_closed_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_tickets', to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.queue')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RerouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('previous_queue', models.CharField(blank=True, max_length=120)),
                ('previous_assignee', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reroute_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_reroute_requests', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reroute_requests', to='tickets.ticket')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_family', models.CharField(choices=[('joint', 'Joint'), ('separate', 'Separate')], max_length=24)),
                ('model_version', models.CharField(max_length=120)),
                ('predicted_queue', models.CharField(blank=True, max_length=120)),
                ('predicted_priority', models.CharField(blank=True, max_length=16)),
                ('queue_confidence_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priority_confidence_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_method', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tickets.ticket')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='tickets.queue')),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.PROTECT, related_name='queue_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-active', 'staff__first_name', 'staff__last_name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('staff',), name='one_active_queue_per_staff')],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'queue'], name='tickets_tic_status_aaef1f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'assigned_to'], name='tickets_tic_status_542056_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer', 'status'], name='tickets_tic_custome_ce12f4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['routing_failed', 'status'], name='tickets_tic_routing_ef1359_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['first_reply_due_at', 'resolution_due_at'], name='tickets_tic_first_r_5ce406_idx'),
        ),
    ]
